version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: iinservice_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    image: iinservice_app
    container_name: iinservice_app
    environment:
      - DATASTORE_URL=mongodb://mongo:27017
      - DATASTORE_DB=iinservice
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - mongo


volumes:
  mongo_data:
